### ISSUE TITLE
Add optional dump of Terraform outputs to a local file 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/terraform-seqera-aws#23]
For the sake of the automation of the Ec2 deployment it would be usual to add in the terraform script the ability to dump the [output params](https://github.com/seqeralabs/platform-installer/blob/master/aws-ec2/templates/main.template.tf#L40C1-L48) into a local file.  

Ideally having this format: 

```
export TOWER_HOSTNAME=<value>
export TOWER_DB_HOSTNAME=<value>
export TOWER_REDIS_HOSTNAME=<value>
```

**Comment by pditommaso** [comment]
> This TOWER_HOSTNAME is a value that Terraform is not handling.

Why not, it's [this](https://github.com/seqeralabs/seqera-installer/blob/79392e1ccf9cc9664ecad45b242386b8b9663cd9/aws-ec2/templates/main.template.tf#L47-L47)

**Comment by HLWiencko** [comment]
I'd be curious to get this in front of customers before making this particular change, just to see if it's something that people ask for. We might be over-anticipating. Can we keep this suggestion in our back pockets for a future iteration if customers need it?

**Comment by pditommaso** [comment]
> Well, technically speaking this is the DNS name of the EC2 instance

Not a useful comment

**Comment by pditommaso** [comment]
Solved
